### ISSUE TITLE
Does the PartsLibrary work for circular sequences?

### ISSUE THREAD

**Issue by avemeva** [Edinburgh-Genome-Foundry/DnaWeaver#5]
### Context
I have a setup of:
- Golden gate parts library supplier with expression vectors.
- Gene synthesis supplier.
- Golden Gate assembly station.

I have uploaded the backbone sequence to the `GoldenGatePartsLibrary`, expecting DnaWeawer to find it.

I am giving the library a `final` sequence of expression vector with inserted gene as input.

### Expected behavior:
- Gene being synthesized
- Backbone being taken from the parts library

### Actual behaviour:
- Everything is synthesised and assembled with GoldenGate

### Question:
Q: Does the PartsLibrary work for circular sequences?

**Comment by avemeva** [comment]
If I understand correctly, for PartsLibrary to support the circular sequences, the sequence decomposer has to work differently, or the sequence has to be re-indexed so that it started with insert. In this case, the sequence decomposer will find it.

**Comment by Zulko** [comment]
It is difficult to say for sure without a minimal runnable example but I believe you are right in your assumptions:
- DnaWeaver expects backbones to be represented like other parts: the linear sequence of the backbone that will end up in the final constructs, flanked by two restriction sites. If you loaded the complete backbone (as a circular construct) the parts library won't know what to do with it. 
- DnaWeaver won't deal correctly with parts and backbones if they are appear cut in the `final` sequence you submit (e.g. one bit of the backbone of the left and another bit on the right).

Does that make sense?

**Comment by avemeva** [comment]
Yeah, it does! I will try to play with it. Thanks, @Zulko!
